// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission06_mnnorton.Models;

namespace Mission06_mnnorton.Migrations
{
    [DbContext(typeof(MovieContext))]
    partial class MovieContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission06_mnnorton.Models.ApplicationResponse", b =>
                {
                    b.Property<int>("MovieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("MovieTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MovieID");

                    b.ToTable("Responses");

                    b.HasData(
                        new
                        {
                            MovieID = 1,
                            Edited = false,
                            MovieTitle = "Legally Blonde",
                            Notes = "This one makes me want to be a girl boss.",
                            Rating = "PG-13"
                        },
                        new
                        {
                            MovieID = 2,
                            Edited = false,
                            MovieTitle = "Cars",
                            Rating = "G"
                        },
                        new
                        {
                            MovieID = 3,
                            Edited = false,
                            MovieTitle = "How to Lose a Guy in Ten Days",
                            Notes = "Caleb likes this one too.",
                            Rating = "PG-13"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
